//COMENTÁRIO DE UMA LINHA
console.log('Linha 1');

/*COMENTÁRIO 
DE MÚLTIPLAS 
LINHAS */
console.log('Linha 2');

/*
*COMENTÁRIO
*DE MÚLTPLAS
*LINHAS
*/
console.log('Linha 3');

/*ATENÇÃO:
* CUIDADO COM COMENTÁRIOS IRRELAVANTES;
* BUSCAR ESCREVER CÓDIGOS LEGÍVEIS;
* COMENTE TUDO QUE FOR NECESSÁRIO PARA A APRENDIZAGEM;
*/
